language: ruby

dist: trusty

rvm:
  - 2.1.8
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6.1

gemfile:
  - Gemfile

script: bundle exec rspec spec

sudo: false

cache: bundler

install:
  # Replace default Travis CI bundler script with a version that doesn't
  # explode when lockfile doesn't match recently bumped version
  - bundle install --no-deployment --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}
