---
name: Tests
'on':
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  test_bundler_1:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: 2.1.9
            gemfile: Gemfile.2.1
    env:
      BUNDLE_GEMFILE: "${{ matrix.gemfile }}"
    steps:
      - uses: actions/checkout@v2
      - name: Install ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "${{ matrix.ruby }}"
      - name: Bundle
        run: |
          gem install bundler:1.17.3
          bundle install --no-deployment
      - name: Run tests
        run: bundle exec rspec

  test_bundler_2:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
        - ruby: 2.3.8
          gemfile: Gemfile
        - ruby: 2.4.5
          gemfile: Gemfile
        - ruby: 2.5.3
          gemfile: Gemfile
        - ruby: 2.6.1
          gemfile: Gemfile
        - ruby: 2.7.3
          gemfile: Gemfile
        - ruby: 3.0.1
          gemfile: Gemfile
    env:
      BUNDLE_GEMFILE: "${{ matrix.gemfile }}"
    steps:
    - uses: actions/checkout@v2
    - name: Install ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "${{ matrix.ruby }}"
    - name: Bundle
      run: |
        gem install bundler:2.2.21
        bundle install --no-deployment
    - name: Run tests
      run: bundle exec rspec
